# Generated by Django 5.2.1 on 2025-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('chassi', models.CharField(max_length=50, unique=True)),
                ('numero_motor', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=30)),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('tipo_placa', models.CharField(choices=[('OFICIAL', 'Oficial'), ('PARTICULAR', 'Particular')], default='OFICIAL', max_length=15)),
                ('grupo', models.CharField(choices=[('A', 'Representação'), ('B', 'Transporte Institucional'), ('C', 'Serviço Comum'), ('D', 'Coletivo/Judicial'), ('E', 'Carga Leve'), ('F', 'Carga Pesada'), ('G', 'Apoio Especial'), ('H', 'Blindado'), ('I', 'Motocicleta'), ('X', 'Sem Classificação')], max_length=1)),
                ('capacidade', models.PositiveIntegerField()),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.CharField(max_length=100)),
                ('documento_fornecedor', models.CharField(max_length=100)),
                ('certificado', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_patrimonial', models.CharField(blank=True, max_length=50, null=True)),
                ('seguradora', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_apolice', models.CharField(blank=True, max_length=50, null=True)),
                ('chip_identificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
