# Generated by Django 5.2.1 on 2025-05-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_frota.grupoveiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_frota.tipoplaca'),
        ),
    ]
