# Generated by Django 5.2.1 on 2025-05-22 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_frota', '0003_veiculo_complemento_abs_veiculo_complemento_ac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIATURA', 'Viatura'), ('MOTORISTA', 'Motorista')], max_length=20)),
                ('unidade', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('data_utilizacao', models.DateField()),
                ('horario', models.CharField(max_length=20)),
                ('itinerario', models.TextField()),
                ('natureza_servico', models.TextField()),
                ('autenticacao_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('autenticacao_motorista', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_saida', models.CharField(blank=True, max_length=20, null=True)),
                ('hora_chegada', models.CharField(blank=True, max_length=20, null=True)),
                ('km_saida', models.CharField(blank=True, max_length=20, null=True)),
                ('km_chegada', models.CharField(blank=True, max_length=20, null=True)),
                ('ocorrencias', models.TextField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_frota.veiculo')),
            ],
        ),
    ]
