# Generated by Django 5.2.1 on 2025-05-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_frota', '0004_requisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='km_chegada',
        ),
        migrations.AddField(
            model_name='requisicao',
            name='km_entrada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='km_saida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
