# Generated by Django 5.2.1 on 2025-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_frota', '0005_remove_requisicao_km_chegada_requisicao_km_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='autenticacao_motorista',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='autenticacao_usuario',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='hora_chegada',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='hora_saida',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='natureza_servico',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='ocorrencias',
        ),
        migrations.AddField(
            model_name='requisicao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='itinerario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='tipo',
            field=models.CharField(choices=[('Oficial', 'Oficial'), ('Particular', 'Particular')], max_length=20),
        ),
    ]
