from .login_views import login_ad_view, logout_view
from .menu_views import menu_view
from .cadastrar_veiculos_views import cadastrar_veiculos_views
from .editar_veiculos_views import editar_veiculo_view
from .excluir_veiculos_views import excluir_veiculo_view
from .listar_veiculos_views import listar_veiculos_views
from .cadastrar_requisicao_views import cadastrar_requisicao_view
from .editar_requisicao_views import editar_requisicao_view
from .excluir_requisicao_views import excluir_requisicao_view
from .listar_requisicao_views import listar_requisicao_view